machines:
  path: "machines" #stores machines_path, relative path for machines folders
  vagrant_provider: hyperv
  list:  #list of machine definitions each child defines a vm
    kubenode1:
      vagrant:  #Any key here will be used to try to override keys in the vagrantfile_template
        node: kubnode0
        hostname: kubhost0
        memory: 2048
        cpus: 1
      ansible:  #Will be added to ansible host definition
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_become: true
      vagrantfile_template: default  #Vagrantfile template. If not specified defaults to "default"
    kubenode2:
      vagrant:
        memory: 2100 #Any parameters specified overrides defaults
      machine_template: default  #use default: config from machine defaults
    kubenode3:  #With no defined parameters defaults to 'machine_template: default'  'vagrantfile_template: default'
machine_templates:
  default:
    vagrant:
      memory: 2048
      cpus: 1
    ansible:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_become: true
vagrantfile_templates:
  default:
    "# -*- mode: ruby -*-\n
    # vi: set ft=ruby :\n
    Vagrant.configure(\"2\") do |config|\n
     \thostname = \"{hostname}\"\n
     \tlocale = \"en_US.UTF.8\"\n
     \t# Box\n
     \tconfig.vm.box = \"bento/centos-7.6\"\n
     \tconfig.vm.synced_folder \".\", \"/vagrant\", disabled: true\n
     \tconfig.vm.provider \"hyperv\" do |v|\n
     \t\tv.memory = {memory}\n
     \t\tv.cpus = {cpus}\n
     \t\tv.vmname = \"{node}\"\n
     \tend\n
     \tconfig.vm.provision \"shell\", inline: <<-SHELL\n
     \techo \"vagrant ALL=(ALL) NOPASSWD: ALL\" > /etc/sudoers.d/vagrant\n
     \tchmod 0440 /etc/sudoers.d/vagrant\n
     \tSHELL\n
     end"
children: #copied directly to ansible inventory
  kube-master:
    hosts:
      kubenode1:
      kubenode2:
  kube-node:
    hosts:
      kubenode1:
      kubenode2:
      kubenode3:
  etcd:
    hosts:
      kubenode1:
      kubenode2:
      kubenode3:
  k8s-cluster:
    children:
      kube-master:
      kube-node:
  calico-rr:
    hosts: {}
